language: julia
os: linux

julia:
        - 0.4

notifications:
        email: false

before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -qq update

install:
        - julia -e 'Pkg.add("DataStructures")'; 
        - julia -e 'Pkg.test("DataStructures")'
        - git clone https://github.com/seung-lab/Watershed.jl.git
        - mv Watershed.jl ~/.julia/v0.4/Watershed

script:
        - julia -e 'using Watershed'
