language: julia
os: linux

julia:
        - 0.4

notifications:
        email: false

script:
        - julia -e `Pkg.init(); Pkg.clone(pwd())`
        - julia -e `Pkg.add("DataStructures")`
        - julia -e `Pkg.test("Watershed")`
